name: BubbleGuard
version: '${project.version}'
main: org.sebirka.BubbleGuard
api-version: '1.16'
commands:
  bubbleguard:
    aliases: [bg]
    description: "Показывает статистику BubbleGuard"
    usage: "/<command> stats|reload"
    permission: "BubbleGuard.admin"

  physic:
    aliases: phy
    permission: "BubbleGuard.physic"
  mobspawn:
    aliases: ms
    permission: "BubbleGuard.mob"

